### ISSUE TITLE
[to-ban-hyo3]次週の当番表作成画面を作成する

### ISSUE THREAD

**Issue by togashi-ashita** [og3/to-ban-hyo#32]

**Comment by og3** [comment]
### 仕様
・週ごと当番表と完了状況を見られるようにする
・roomとroleを閲覧、変更できるようにする
・当番表のレコード編集、roomのfixを切り替え、期間を切り替えられるようにする
・期間を変更したら新しいレコードとして保存するようにする

**Comment by og3** [comment]
### 仕様
・管理画面に直近の当番表を出す（次週の当番表作成画面）
・ここで変更後の当番表を作成できるようにする
・start_of_periodを次の配信日にした場合
・rake_taskの表の取得条件に「今日と直近のstart_of_periodが同じだったらreturnする処理」を追加する

**Comment by og3** [comment]
### ビューとアクション
#### tobanhyo_controller
- index
@tobanhyos = Tobanhyo.all.group_by(&:start_of_period)
期間ごとにまとめてもらって、見出しではそれを並べたい
viewでは期間のみ表示する

- show、edit
@tobanhyo = Tobanhyo.where(params: start_of_period)
indexから飛んだ時に期間の値を持って飛ぶ
- update、create
saveのアクション
#### この２つはまだいらない？
- new
- delete

**Comment by og3** [comment]
### formで一括でレコードを作りたい

**Comment by og3** [comment]
fields_forを使う気がする。gemっはいらないと思うけど。
https://www.virment.com/add_and_remove_rails_nested_form_dynamically/

**Comment by og3** [comment]
●やりたいこと
人の入れ替わりがあった時に、先週の当番表を元に新しい当番表を作りたい

●参考
http://j-caw.co.jp/blog/?p=1590

●実装方法
・controller
  def new
    @new_tobanhyo = Tobanhyo.new
    # 先週の当番表をコピーする
    @tobanhyo = Tobanhyo.where(start_of_period: params[:start_of_period]).map(&:dup)
    # プルダウンで選択できるように、部屋・役割の一覧をハッシュで作成する
    @rooms = {}
    @roles = {}
    @tobanhyo.each do |hyo|
      @rooms[hyo.room.name] = hyo.room.id
      @roles[hyo.role.name] = hyo.role.id
    end
    # 役割が固定かどうかでグルーピングする
    @tobanhyos = @tobanhyo.group_by(&:fixed)
  end

・入力フォーム
= Time.zone.today.strftime('%Y/%m/%d')
= form_for @new_tobanhyo do |f|
  - @tobanhyos[false].each do |tobanhyo|
    = fields_for "tobans[]", tobanhyo do |fi|
      p
        = fi.select :room_id, @rooms, :selected => tobanhyo.room.id
        = fi.select :role_id, @roles, :selected => tobanhyo.role.id
        = fi.select :fixed, [true, false], :selected => false
        = fi.date_field :start_of_period
  = "---------------------"
  - @tobanhyos[true].each do |tobanhyo|
    = fields_for "tobans[]", tobanhyo do |fi|
        p
          = fi.select :room_id, @rooms, :selected => tobanhyo.room.id
          = fi.select :role_id, @roles, :selected => tobanhyo.role.id
          = fi.select :fixed, [true, false], :selected => true
          = fi.date_field :start_of_period
  = f.submit


・ログ
Started POST "/tobanhyos" for 127.0.0.1 at 2018-09-02 16:22:56 +0900
Processing by TobanhyosController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"6erkKG/b2xLzfAtHTW0hTLG7W4VwyYj4PgK2Rg5HbDHjCTj8+vYwKfBiepcK9RqBoTN0B5z5UoRAcFi9SeHx8w==", "tobans"=>[{"room_id"=>"1", "role_id"=>"3", "fixed"=>"false", "start_of_period"=>"2018-08-26"}, {"room_id"=>"2", "role_id"=>"8", "fixed"=>"false", "start_of_period"=>"2018-08-26"}, {"room_id"=>"3", "role_id"=>"1", "fixed"=>"false", "start_of_period"=>"2018-08-26"}, {"room_id"=>"4", "role_id"=>"2", "fixed"=>"false", "start_of_period"=>"2018-08-26"}, {"room_id"=>"5", "role_id"=>"3", "fixed"=>"false", "start_of_period"=>"2018-08-26"}, {"room_id"=>"6", "role_id"=>"6", "fixed"=>"false", "start_of_period"=>"2018-08-26"}, {"room_id"=>"7", "role_id"=>"4", "fixed"=>"false", "start_of_period"=>"2018-08-26"}, {"room_id"=>"8", "role_id"=>"3", "fixed"=>"false", "start_of_period"=>"2018-08-26"}, {"room_id"=>"10", "role_id"=>"7", "fixed"=>"false", "start_of_period"=>"2018-08-26"}, {"room_id"=>"11", "role_id"=>"3", "fixed"=>"false", "start_of_period"=>"2018-08-26"}, {"room_id"=>"13", "role_id"=>"5", "fixed"=>"false", "start_of_period"=>"2018-08-26"}, {"room_id"=>"14", "role_id"=>"9", "fixed"=>"false", "start_of_period"=>"2018-08-26"}, {"room_id"=>"9", "role_id"=>"11", "fixed"=>"true", "start_of_period"=>"2018-08-26"}, {"room_id"=>"12", "role_id"=>"10", "fixed"=>"true", "start_of_period"=>"2018-08-26"}], "commit"=>"Create Tobanhyo"}

・ストロングパラメータ
  private
    def tobans_params
      params.permit(tobans: [:room_id, :role_id, :fixed, :start_of_period])[:tobans]
    end


●問題点
・以下をどうやって１つのレコードとして保存していいかわからない
ログ
Started POST "/tobanhyos" for 127.0.0.1 at 2018-09-02 16:22:56 +0900
Processing by TobanhyosController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"6erkKG/b2xLzfAtHTW0hTLG7W4VwyYj4PgK2Rg5HbDHjCTj8+vYwKfBiepcK9RqBoTN0B5z5UoRAcFi9SeHx8w==", "tobans"=>[{"room_id"=>"1", "role_id"=>"3", "fixed"=>"false", "start_of_period"=>"2018-08-26"}, {"room_id"=>"2", "role_id"=>"8", "fixed"=>"false", "start_of_period"=>"2018-08-26"}, {"room_id"=>"3", "role_id"=>"1", "fixed"=>"false", "start_of_period"=>"2018-08-26"}, {"room_id"=>"4", "role_id"=>"2", "fixed"=>"false", "start_of_period"=>"2018-08-26"}, {"room_id"=>"5", "role_id"=>"3", "fixed"=>"false", "start_of_period"=>"2018-08-26"}, {"room_id"=>"6", "role_id"=>"6", "fixed"=>"false", "start_of_period"=>"2018-08-26"}, {"room_id"=>"7", "role_id"=>"4", "fixed"=>"false", "start_of_period"=>"2018-08-26"}, {"room_id"=>"8", "role_id"=>"3", "fixed"=>"false", "start_of_period"=>"2018-08-26"}, {"room_id"=>"10", "role_id"=>"7", "fixed"=>"false", "start_of_period"=>"2018-08-26"}, {"room_id"=>"11", "role_id"=>"3", "fixed"=>"false", "start_of_period"=>"2018-08-26"}, {"room_id"=>"13", "role_id"=>"5", "fixed"=>"false", "start_of_period"=>"2018-08-26"}, {"room_id"=>"14", "role_id"=>"9", "fixed"=>"false", "start_of_period"=>"2018-08-26"}, {"room_id"=>"9", "role_id"=>"11", "fixed"=>"true", "start_of_period"=>"2018-08-26"}, {"room_id"=>"12", "role_id"=>"10", "fixed"=>"true", "start_of_period"=>"2018-08-26"}], "commit"=>"Create Tobanhyo"}

・ストロングパラメータの各記述の意味がわからない
  private
    def tobans_params
      params.permit(tobans: [:room_id, :role_id, :fixed, :start_of_period])[:tobans]
    end

・form_forだとうまくいかない
@new_tobanhyoに値が入っていない
やはり参考
入力フォーム
= Time.zone.today.strftime('%Y/%m/%d')
= form_for @new_tobanhyo do |f|
  - @tobanhyos[false].each do |tobanhyo|
    = fields_for "tobans[]", tobanhyo do |fi|
      p
        = fi.select :room_id, @rooms, :selected => tobanhyo.room.id
        = fi.select :role_id, @roles, :selected => tobanhyo.role.id
        = fi.select :fixed, [true, false], :selected => false
        = fi.date_field :start_of_period
  = "---------------------"
  - @tobanhyos[true].each do |tobanhyo|
    = fields_for "tobans[]", tobanhyo do |fi|
        p
          = fi.select :room_id, @rooms, :selected => tobanhyo.room.id
          = fi.select :role_id, @roles, :selected => tobanhyo.role.id
          = fi.select :fixed, [true, false], :selected => true
          = fi.date_field :start_of_period
  = f.submit



●挑戦
・createの部分で配列をeachで回して保存するのでは？

●解決
ストロングパラメータの設定を以下のようにすると、ログがいい感じになる
  private
    def tobans_params
      # 第二引数の[:tobans]をつけないと[tobans,[各種paramsの値]]となってmapで回せなくなってしまう
      params.permit(tobans: [:room_id, :role_id, :fixed, :start_of_period])[:tobans]
    end

入力欄
= Time.zone.today.strftime('%Y/%m/%d')
= form_tag '/tobanhyos', method: :post do
  - @tobanhyos[false].each do |tobanhyo|
    = fields_for "tobans[]", tobanhyo do |fi|
      p
        = fi.select :room_id, @rooms, :selected => tobanhyo.room.id
        = fi.select :role_id, @roles, :selected => tobanhyo.role.id
        = fi.select :fixed, [true, false], :selected => false
        = fi.date_field :start_of_period, value: Time.zone.today.strftime("%Y-%m-%d")
  = "---------------------"
  - @tobanhyos[true].each do |tobanhyo|
    = fields_for "tobans[]", tobanhyo do |fi|
        p
          = fi.select :room_id, @rooms, :selected => tobanhyo.room.id
          = fi.select :role_id, @roles, :selected => tobanhyo.role.id
          = fi.select :fixed, [true, false], :selected => true
          = fi.date_field :start_of_period, value: Time.zone.today.strftime("%Y-%m-%d")
  = submit_tag

**Comment by og3** [comment]
●staging環境でテストする
テスト事項
①
・作成画面で新規に当番表を作成する
・実行日の日付の当番表があった場合、作成処理をスキップする

●手順
１、rakeタスクを起動する
`heroku rake send_to_ban_hyo:tobanhyo --app to-ban-hyo --remote staging`
２、確認する

エラー発見
決め打ちしている日付取得の部分でエラーが出ている
