### ISSUE TITLE
各種マスターの作成・編集・削除ができるようにする

### ISSUE THREAD

**Issue by togashi-ashita** [og3/to-ban-hyo#42]
部屋と役割のマスターをCRUDできるようにする

**Comment by og3** [comment]
## やること
・room,roleのそれぞれにnew,create,edit,update,deleteができるようにする
・サクセス、エラーメッセージを表示する
・バリデーションをかける
・画面遷移はサクセス時には一覧に返す、エラー時はその画面をrenderする
### ROOM
　name：入力必須（DBの方もそうやって設定すること）
　login_id：入力必須、ユニークであること
　パスワード：入力必須
　パスワード確認：パスワードと内容がイコールかどうか検証する
### ROLE
　name：入力必須（DBの方もそうやって設定すること）
### TOBANHYO
　完全NEWができるようにする（このチケットでやるかどうかは迷う）
　編集と削除はできなくてもいいかと思う

**Comment by og3** [comment]
## 参考
・バリデーション
https://qiita.com/shunhikita/items/772b81a1cc066e67930e

**Comment by og3** [comment]
turbolinksがONでテーブル内にフォームがあるとsubmitできない
https://qiita.com/hc_isobe/items/cfe1f31319780e73cebe
